### ISSUE TITLE
sender messages are displaying twice on the sender side

### ISSUE THREAD

**Issue by XLG123** [XLG123/JMAX#55]
**Render** is currently not affected because it's not using the main branch
**Main branch** is currently affected

**Comment by j-corp-25** [comment]
this issues has been resolved, the bug was happening because it was "emitting" and saving. which was causing two saves, i put a conditional save after emitting if it exists which only saves once now. I also put a reference to the scroll container, so now when you type if scrolls up. makes it so much better for the user experience.
